# Site Settings
lang: en
title: Edward Garcia's CS499 Capstone ePortfolio
tagline: Showcasing my Capstone Artifacts and Enhancements
email: edward.garcia@example.com  # Replace with your actual email
description: >
  A portfolio site showcasing Edward Garcia's CS499 Capstone artifacts, enhancements, and professional growth.
baseurl: "/CS499-ePortfolio"
url: "https://devopulent.github.io"
permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: edwardgarcia
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
force_theme: light

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: ""  # Leave blank to disable comments

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-XXXXXX-Y  # Add your Google Analytics tracking code if available
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Edward Garcia"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

social:
  facebook: https://www.facebook.com/edwardgarcia  # Replace with your actual link
  instagram: https://www.instagram.com/edwardgarcia  # Replace with your actual link
  threads: https://www.threads.net/edwardgarcia  # Replace if applicable
  tiktok: https://www.tiktok.com/@edwardgarcia  # Replace with your actual link
  x: https://www.x.com/edwardgarcia  # Replace with your actual link
  youtube: https://www.youtube.com/edwardgarcia  # Replace with your actual link
